import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
      <main className="min-h-screen">
        <TooltipProvider>
          {children}
        </TooltipProvider>
      </main>
      </body>
    </html>
  );
}
