import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider } from "@/components/global/ThemeProvider";
import Navbar from "@/components/global/Navbar";


const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
        <main className="min-h-screen">
          <TooltipProvider>
            <Navbar/>
            {children}
          </TooltipProvider>
        </main>
      </ThemeProvider>
      </body>
    </html>
  );
}